//
// Created by TSH-STUDIO 唐诗涵 on 25-1-23.
//

#ifndef TEAM3CAPYBARA_SYSTEM_CODE_SYSTEM_CODE_H
#define TEAM3CAPYBARA_SYSTEM_CODE_SYSTEM_CODE_H

enum Canset_state{
  INFLIGHT,
  LANDED,
  ROVERING1,
  ROVERING2,
  RECOVERY
};

#endif //TEAM3CAPYBARA_SYSTEM_CODE_SYSTEM_CODE_H
